- name: Install ngnix
  hosts: web
  become: yes
  tasks:
  - name: install ngnix if RHEL
    ansible.builtin.dnf:
      name: ngnix
      state: installed
    when: ansible_os_family == "RedHat"
  
  - name: install ngnix if Ubentu
    ansible.builtin.apt:
      name: ngnix
      state: installed
    when: ansible_os_family == "Debian"