- name: create ec2 instances and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0aa3e0ba4c8cc9e93
    sg_id: sg-0b169e25a04266e00
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    origin: us-east-1
    zone: parijathapractice.online
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: install aws python libraries
    anible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
    register: ec2_info
    
  - name: print ec2_info
    ansible.builtin.debug:
      msg: "{{ ec2_info }}"
    